# Header
menu:
  主页: /
  所有文章: /archives
  随笔总结: /categories/随笔
  学习笔记: /categories/笔记

# SubNav
subnav:
  github: "http://springxiege.gitbub.io"
  weibo: "http://weibo.com/springxiege"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto://springxiege@sina.cn"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: https://github.com/fluidicon.png

#你的头像url
avatar: http://ww4.sinaimg.cn/mw690/8f4c7b1djw8f2fa9x9bugj20b50b5q3l.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  乱码大大的博客: http://www.52cik.com/
  菜青虫的博客: http://webcaiqingchong.github.io/
  #卡卡的美丽传说: http://localhost:4000/
  #本泽马的博客: http://localhost:4000/
  #吉格斯的博客: http://localhost:4000/
  #习大大大不同: http://localhost:4000/
  #托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我就是心情
